services:
  # This is your main PHP web application
  - type: web
    name: newmann-app
    env: php
    plan: free
    dockerfilePath: ./render.dockerfile
    
    # Environment variables for the database connection
    envVars:
      - key: DB_HOST
        fromService:
          type: p-mysql # This is the corrected type
          name: newmann-db
          property: host
      - key: DB_USER
        fromService:
          type: p-mysql # This is the corrected type
          name: newmann-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: p-mysql # This is the corrected type
          name: newmann-db
          property: password
      - key: DB_NAME
        fromService:
          type: p-mysql # This is the corrected type
          name: newmann-db
          property: database

  # This is your MySQL database
  - type: p-mysql # <-- THIS IS THE CORRECTED LINE
    name: newmann-db
    region: singapore # Or your chosen region
    plan: free
    version: '8.0'