services:
  - type: web
    name: newmann-app
    runtime: docker
    dockerfilePath: ./render.dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newmann-db-pg
          property: connectionString

  - type: pserv
    name: newmann-db-pg
    region: singapore
    plan: free