services:
  # This is your main PHP web application
  - type: web
    name: newmann-app
    # The 'env: php' line has been removed to allow the Dockerfile to be used
    plan: free
    dockerfilePath: ./render.dockerfile
    
    # Environment variables for the database connection
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newmann-db-pg
          property: connectionString

  # This is your PostgreSQL database
  - type: pserv 
    name: newmann-db-pg
    region: singapore # Or your chosen region
    plan: free