services:
  # This is your main PHP web application
  - type: web
    name: newmann-app
    # We specify 'docker' as the environment to explicitly use our Dockerfile
    env: docker
    plan: free
    # We can remove the explicit path as Render finds it by default
    # dockerfilePath: ./render.dockerfile
    
    # Environment variables for the database connection
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newmann-db-pg
          property: connectionString

  # This is your PostgreSQL database
  - type: pserv 
    name: newmann-db-pg
    region: singapore # Or your chosen region
    plan: free